// Package items serves the per-map pickup-item corpus to the analyzer
// pipeline. Data is generated by qwanalytics/cmd/mapgen (BSP entities
// lump) and shipped two ways:
//
//   - Native / CLI / tests: embedded at compile time via go:embed.
//   - WASM / browser: fetched synchronously from the JS host via a
//     fetchItemsSync(mapName) callback the worker installs.
//
// The public API is LoadForMap(mapName) → ([]MapItem, error), mirroring
// qwanalytics/loc. Normalisation of map names also mirrors loc.
package items

// MapItem is one pickup on a map. Keep this struct in sync with
// qwanalytics/mapgen/mapgeom.MapItem — they share the JSON shape.
type MapItem struct {
	Kind string  `json:"kind"`
	X    float32 `json:"x"`
	Y    float32 `json:"y"`
	Z    float32 `json:"z"`
}

// fileFormat is the on-disk shape of data/<map>.json. Kept unexported;
// callers use LoadForMap which returns the inner slice.
type fileFormat struct {
	Map     string    `json:"map"`
	Version int       `json:"version"`
	Items   []MapItem `json:"items"`
}

// NormalizeMapName lowercases and strips the ".bsp" suffix so "DM6.bsp"
// and "dm6" resolve to the same corpus entry. Duplicated from loc so
// the two packages stay independent.
func NormalizeMapName(name string) string {
	out := make([]byte, 0, len(name))
	for i := 0; i < len(name); i++ {
		c := name[i]
		if c >= 'A' && c <= 'Z' {
			c += 'a' - 'A'
		}
		out = append(out, c)
	}
	s := string(out)
	if len(s) > 4 && s[len(s)-4:] == ".bsp" {
		s = s[:len(s)-4]
	}
	return s
}
